-- Create this in Supabase Dashboard → SQL Editor → Run
create table public.daily_outlet_sales (
  id bigint generated by default as identity primary key,
  date date not null,
  loc_code text not null,
  loc_name text,
  net_sales numeric not null default 0,
  constraint daily_outlet_sales_unique unique (date, loc_code)
);

-- Indexes for fast aggregation queries
create index daily_outlet_sales_date_idx on public.daily_outlet_sales (date);
create index daily_outlet_sales_loc_code_idx on public.daily_outlet_sales (loc_code);

-- Row-level security (service role bypasses this, but good practice)
alter table public.daily_outlet_sales enable row level security;

-- Allow all authenticated access for reading (anon key)
create policy "Allow read" on public.daily_outlet_sales for select using (true);
-- Allow service role full access
create policy "Service role full access" on public.daily_outlet_sales for all using (true);
